version: '3.8'
services:
  soap-web:
    image: tubes-2-soap:latest
    ports:
      - "8001:8001"
    env_file: .env
    volumes:
      - ./src:/app/src
    networks:
      - soap-services
  mysql-soap:
    image: mysql:latest
    ports:
      - "3309:3306"
    env_file: .env
    hostname: db-soap-service
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - soap-services
volumes:
  db:
    driver: local
networks:
  soap-services:
    driver: bridge