version: "3.9"
services:
  php-web:
    extends:
      file: ./src/php/docker-compose.yml
      service: web
    networks:
      - cari-jodoh
  php-db:
    extends:
      file: ./src/php/docker-compose.yml
      service: mysql
    networks:
      - cari-jodoh
  mysql-rest:
    extends:
      file: ./src/rest/docker-compose.yml
      service: mysql-rest
    networks:
      - cari-jodoh
  redis:
    extends:
      file: ./src/rest/docker-compose.yml
      service: redis
    networks:
      - cari-jodoh
  rest-web:
    depends_on:
      - mysql-rest
      - redis
    extends:
      file: ./src/rest/docker-compose.yml
      service: rest-web
    networks:
      - cari-jodoh
  mysql-soap:
    extends:
      file: ./src/soap/docker-compose.yml
      service: mysql-soap
    networks:
      - cari-jodoh
  soap-web:
    depends_on:
      - mysql-soap
    extends:
      file: ./src/soap/docker-compose.yml
      service: soap-web
    networks:
      - cari-jodoh
  spa:
    extends:
      file: ./src/spa/docker-compose.yml
      service: spa
    networks:
      - cari-jodoh

networks:
  cari-jodoh:
