version: "3.8"
services:
  spa:
    build: ./
    container_name: tubes2-spa
    ports:
      - "5173:5173"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
